// Generated company catalog data
export type Company = {
  id: string;
  name: string;
  city: string;
  voivodeship: string;
  website: string;
  description: string;
  services: string[];
  rating: number;
};

export const companies: Company[] = [
  {
    id: "bydgoszcz-art-studio-2-meble-kuchenne-bydgoszcz-kuchnie-bydgoszcz",
    name: "Art Studio 2 - Meble kuchenne Bydgoszcz kuchnie Bydgoszcz",
    city: "Bydgoszcz",
    voivodeship: "kujawsko-pomorskie",
    website: "https://artstudio2.pl/",
    description: "Meble kuchenne i kuchnie Bydgoszcz . Secjalizujemy się w projektowaniu kuchni i sprzedaży mebli kuchennych w Bydgoszczy.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.7,
  },
  {
    id: "bydgoszcz-bartex-meble-meble-kuchenne-na-wymiar-bydgoszcz",
    name: "Bartex Meble: Meble kuchenne na wymiar Bydgoszcz",
    city: "Bydgoszcz",
    voivodeship: "kujawsko-pomorskie",
    website: "https://www.bartex-meble.pl/",
    description: "Bartex to firma z 29-letnim doświadczeniem w Bydgoszczy, specjalizująca się w kompleksowej obsłudze klienta - od doradztwa i projektowanie, przez wykonanie, aż po montaż mebli na zamówienie. Tworzymy funkcjonalne i stylowe kuchnie, pomagając w doborze…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.8,
  },
  {
    id: "bydgoszcz-dual-studio-mebli-kuchennych-meble-kuchenne-bydgoszcz",
    name: "DUAL - STUDIO MEBLI KUCHENNYCH - Meble kuchenne Bydgoszcz.",
    city: "Bydgoszcz",
    voivodeship: "kujawsko-pomorskie",
    website: "https://dualkuchnie.pl/",
    description: "Pracujemy ciężko, łączymy stawiane przed nami wyzwania z możliwościami marki Dual kreując najlepsze dla Was rozwiązania. Tworząc z myślą o Waszych pasjach, oczekiwaniach i marzeniach pozyskujecie studio mebli full service 360°. Prowadzimy strategię, którą…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Nowoczesne kuchnie"],
    rating: 4.9,
  },
  {
    id: "bydgoszcz-kuchnie-imianowski-meble-premium-showroom-bydgoszcz-torun",
    name: "Kuchnie Imianowski - Meble Premium - Showroom Bydgoszcz & Toruń ...",
    city: "Bydgoszcz",
    voivodeship: "kujawsko-pomorskie",
    website: "https://imian-kuchnie.pl/",
    description: "Meble kuchenne Każdy projekt zaczyna się od rozmowy - o tym, co ważne, co inspiruje i co sprawia, że kuchnia staje się naprawdę „Twoja\".",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.5,
  },
  {
    id: "bydgoszcz-kuchnie-na-wymiar-bydgoszcz-meble-kuchenne-projekt-kuchni",
    name: "Kuchnie na wymiar Bydgoszcz | Meble kuchenne | Projekt kuchni",
    city: "Bydgoszcz",
    voivodeship: "kujawsko-pomorskie",
    website: "https://kuchnie-bydgoszcz.com/",
    description: "Kuchnie na wymiar Bydgoszcz Inwestycja w meble kuchenne na zamówienie przynosi istotne korzyści, które są szczególnie ważne w kontekście personalizacji i maksymalnego wykorzystania przestrzeni kuchennej.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.6,
  },
  {
    id: "bydgoszcz-meble-kuchenne-bydgoszcz-funkcjonalnosc-i-styl-w-twoim-domu",
    name: "Meble kuchenne Bydgoszcz - funkcjonalność i styl w Twoim domu",
    city: "Bydgoszcz",
    voivodeship: "kujawsko-pomorskie",
    website: "https://meblekuchenne.pl/meble-kuchenne-bydgoszcz/",
    description: "Meble kuchenne w Bydgoszcz - projektujemy i wykonujemy kuchnie na wymiar. Styl i jakość w najlepszej cenie! Skontaktuj się z nami już dziś.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie"],
    rating: 4.8,
  },
  {
    id: "bydgoszcz-meble-kuchenne-bydgoszcz-kuchnie-na-wymiar-domo-studio-mebli",
    name: "Meble kuchenne Bydgoszcz Kuchnie na wymiar Domo Studio Mebli",
    city: "Bydgoszcz",
    voivodeship: "kujawsko-pomorskie",
    website: "https://www.studiokuchni.com/",
    description: "Meble kuchenne , kuchnie na wymiar, na zamówienie w Domo Studio Mebli Kuchennych w Bydgoszczy. Projekty kuchni, mebli kuchennych Bydgoszcz .",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Nowoczesne kuchnie"],
    rating: 4.9,
  },
  {
    id: "bydgoszcz-meble-kuchenne-bydgoszcz-szafy-z-drzwiami-przesuwnymi-inspiracja",
    name: "Meble kuchenne Bydgoszcz, Szafy z drzwiami przesuwnymi - INSPIRACJA",
    city: "Bydgoszcz",
    voivodeship: "kujawsko-pomorskie",
    website: "https://kuchnie-bydgoszcz.info.pl/",
    description: "Oferujemy najwyższej jakości meble kuchenne renomowanej marki ATLAS oraz doskonale spasowane pod potrzeby klienta szafy z drzwiami przesuwnymi i garderoby.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.6,
  },
  {
    id: "bydgoszcz-meble-kuchenne-na-zamowienie-kuchnie-na-wymiar-mobiliani-bydgoszcz",
    name: "Meble kuchenne na zamówienie, kuchnie na wymiar - Mobiliani Bydgoszcz",
    city: "Bydgoszcz",
    voivodeship: "kujawsko-pomorskie",
    website: "https://meble-mobiliani.pl/",
    description: "Mobiliani Bydgoszcz oferuje meble kuchenne , kuchnie na wymiar oraz meble na wymiar do biura, hotelu, restauracji czy meble sklepowe - szafy i garderoby.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Sklep internetowy", "Zabudowy", "Klasyczne kuchnie"],
    rating: 4.9,
  },
  {
    id: "bydgoszcz-meble-na-wymiar-bydgoszcz-torun-emmi-kuchnie-producent",
    name: "Meble na wymiar Bydgoszcz, Toruń - Emmi Kuchnie - producent",
    city: "Bydgoszcz",
    voivodeship: "kujawsko-pomorskie",
    website: "https://emmikuchnie.pl/",
    description: "01. Kuchnie na wymiar Bydgoszcz Tworzymy funkcjonalne i estetyczne meble kuchenne , które spełnią Twoje oczekiwania. Idealne połączenie stylu i praktyczności.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.6,
  },
  {
    id: "gdansk-kuchnie-na-wymiar-gdansk-meble-kuchenne-gdanskiekuchnie-pl",
    name: "Kuchnie na Wymiar Gdańsk - Meble Kuchenne | Gdańskiekuchnie.pl",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    website: "https://gdanskiekuchnie.pl/",
    description: "Kuchnie na wymiar Gdańsk - tworzymy meble kuchenne na wymiar w stylu nowoczesnym, klasycznym, skandynawskim, glamour, loftowym, rustykalnym oraz vintage.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Klasyczne kuchnie"],
    rating: 4.7,
  },
  {
    id: "gdansk-kuchnie-na-wymiar-gdansk-meble-kuchenne-gdansk",
    name: "Kuchnie na wymiar Gdańsk - Meble kuchenne Gdańsk",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    website: "https://meblemibu.pl/kuchnie-na-wymiar-gdansk/",
    description: "Meble kuchenne na wymiar Gdańsk - Nasza oferta W naszej ofercie znajdziesz wszystko, co potrzebne do stworzenia wymarzonej kuchni. Dzięki współpracy z najlepszymi projektantami, potrafimy zaprojektować piękne kuchnie, które idealnie wpasują się w przestrzeń…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.4,
  },
  {
    id: "gdansk-kuchnie-na-wymiar-gdansk-kuchnia-na-wymiar-w-gdansku",
    name: "Kuchnie na wymiar Gdańsk | Kuchnia na wymiar w Gdańsku",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    website: "https://mebleuszacki.pl/kuchnie-na-wymiar-gdansk/",
    description: "Kuchnie na wymiar Gdańsk Projektujemy, wykonujemy oraz montujemy meble kuchenne na wymiar na terenie Gdańska, Gdyni i całego Trójmiasta. Od lat specjalizujemy się w tworzeniu unikatowych rozwiązań, które spełniają indywidualne potrzeby naszych klientów.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie"],
    rating: 4.7,
  },
  {
    id: "gdansk-kuchnie-na-wymiar-gdansk-projektowanie-i-realizacja-wnetrz",
    name: "Kuchnie na wymiar Gdańsk | Projektowanie i realizacja wnętrz",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    website: "https://altre.pl/",
    description: "W Altre Kuchnie specjalizujemy się w projektowaniu i realizacji kuchni na wymiar w Gdańsku i okolicach. Tworzymy meble na wymiar, które łączą doskonałą jakość, precyzyjne wykonanie i ponadczasowy design. Dzięki naszemu doświadczeniu dbamy o najdrobniejsze…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.3,
  },
  {
    id: "gdansk-meble-kuchenne-gdansk-agata-sklep",
    name: "Meble kuchenne Gdańsk - Agata Sklep",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    website: "https://www.agatameble.pl/sklep/gdansk/meble-kuchenne",
    description: "Praktyczne meble kuchenne do wyjątkowych wnętrz w Gdańsku Marzysz o kuchni, która będzie idealnie dopasowana do Twoich potrzeb i nawyków? W Gdańsku na meble kuchenne zamówione online nie będziesz długo czekać. Nasi doświadczeni projektanci pomogą Ci…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.7,
  },
  {
    id: "gdansk-meble-kuchenne-na-wymiar-conceptx-gdansk-pasaz-chemski",
    name: "Meble kuchenne na wymiar | ConceptX Gdańsk, Pasaż chełmski.",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    website: "https://www.conceptx.pl/",
    description: "Meble kuchenne na wymiar | Szeroki wybór nowoczesnych mebli w przystępnych cenach. Oferujemy bezpłatny projekt/wizualizację 3D. Zobacz.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Wizualizacje 3D"],
    rating: 4.6,
  },
  {
    id: "gdansk-nowoczesne-kuchnie-na-wymiar-meble-kuchenne-gdansk-meblew",
    name: "Nowoczesne kuchnie na wymiar - Meble kuchenne - Gdańsk MEBLEW",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    website: "https://meblew.com.pl/",
    description: "Tworzymy piękne kuchnie na wymiar Gdańsk . Meble kuchenne na wymiar Gdynia, szafy na wymiar Gdansk , szafki łazienkowe na wymiar, meble do salonu Trójmiasto.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Zabudowy", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.8,
  },
  {
    id: "gdansk-studio-kuchenne-agma-w-gdansku-kompleksowe-wyposazenie-kuchni",
    name: "Studio Kuchenne AGMA w Gdańsku - kompleksowe wyposażenie kuchni",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    website: "https://www.agmakuchnie.pl/",
    description: "Wyposażenie kuchni - Studio Kuchenne Agma z Gdańska W naszym Studiu Kuchennym Agma z Gdańska zajmujemy się kompleksowym wyposażeniem kuchni. Usługa kuchni na wymiar obejmuje projektowanie i montaż mebli kuchennych o dowolnej stylistyce - wśród naszych…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Klasyczne kuchnie"],
    rating: 4.6,
  },
  {
    id: "gdansk-vega-kuchnie-na-wymiar-i-meble-kuchenne-gdansk",
    name: "VEGA KUCHNIE NA WYMIAR i MEBLE KUCHENNE GDAŃSK",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    website: "https://meblevega.pl/",
    description: "PHU Vega to firma z branży meblowej wykonująca meble kuchenne na zamówienie, kuchnie na wymiar, zabudowy kuchenne i pokojowe oraz szafy na wymiar.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Nowoczesne kuchnie"],
    rating: 4.4,
  },
  {
    id: "gdansk-inna-house-meble-kuchenne-gdansk-kuchnia-na-zamowienie",
    name: "inna.house - Meble Kuchenne Gdańsk Kuchnia Na Zamówienie ...",
    city: "Gdańsk",
    voivodeship: "pomorskie",
    website: "https://inna.house/",
    description: "Meble kuchenne na wymiar Gdańsk - oferta mebli do Twojej kuchni Jakiej kuchni potrzebujesz? Stworzymy dla Ciebie przestrzeń nie tylko praktyczną i wygodną, ale też wykorzystującą elementy, które lubisz i dobrze pasującą do wnętrza Twojego domu lub mieszkania.…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.4,
  },
  {
    id: "katowice-katowice-agata",
    name: "Katowice - Agata",
    city: "Katowice",
    voivodeship: "śląskie",
    website: "https://www.agatameble.pl/sklep/katowice/meble-kuchenne",
    description: "Meble tapicerowane dopasujesz do swojej wizji - wiele z nich jest dostępnych na zamówienie, w zróżnicowanej ofercie tkanin. Pracownicy pomogą Ci, jeśli będziesz potrzebował fachowej porady.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.6,
  },
  {
    id: "katowice-kuchnie-katowice-salon-sprzedazy-kuchni-na-wymiar-meble-na",
    name: "Kuchnie Katowice - Salon sprzedaży kuchni na wymiar | Meble na ...",
    city: "Katowice",
    voivodeship: "śląskie",
    website: "https://meble-halupczok.pl/salony-sprzedazy/kuchnie-katowice/",
    description: "SALON MEBLI KUCHENNYCH KATOWICE Meble kuchenne marki Halupczok w Katowicach, są do obejrzenia w galerii Nowy Roździeń. Galeria ta skupia producentów mebli i innego wyposażenia wnętrz wysokiej klasy. Meble kuchenne Halupczok znajdują się na poziomie 01…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Nowoczesne kuchnie"],
    rating: 4.5,
  },
  {
    id: "katowice-kuchnie-i-meble-na-wymiar-katowice-mebe-pl",
    name: "Kuchnie i meble na wymiar Katowice - MEBE.pl",
    city: "Katowice",
    voivodeship: "śląskie",
    website: "https://mebe.pl/",
    description: "Kuchnie i meble na wymiar - Katowice , Śląsk ☎ 607 035 225 ☆ biuro@mebe.com.pl. Projekt, produkcja i montaż mebli na wymiar. Bezpłatny pomiar w Katowicach!",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.5,
  },
  {
    id: "katowice-labryga-kuchnie-i-meble-kuchenne-na-wymiar-katowice-chorzow",
    name: "Labryga - Kuchnie i meble kuchenne na wymiar | Katowice, Chorzów",
    city: "Katowice",
    voivodeship: "śląskie",
    website: "https://labryga.pl/",
    description: "Nasze realizacje to nasza jakość, którą dziś z dumą sygnujemy rodzinnym nazwiskiem. Oprócz kuchni, na zamówienie wykonujemy również meble pokojowe, łazienkowe oraz szafy i garderoby. Działamy na Śląsku i okolicach. Skontaktuj się z nami albo odwiedź nasze…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Nowoczesne kuchnie"],
    rating: 4.4,
  },
  {
    id: "katowice-meble-kuchenne-katowice-amazi",
    name: "Meble Kuchenne Katowice | Amazi",
    city: "Katowice",
    voivodeship: "śląskie",
    website: "http://mebledokuchni.katowice.pl/",
    description: "Sami możemy zaprojektować jakie meble kuchenne katowice tam wstawimy, a firma dostarczy nam meble na zamówienie. Kuchnie na wymiar to dzisiaj podstawowy artykuł który oferują firmy zajmujące się produkcja mebli.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.4,
  },
  {
    id: "katowice-meble-kuchenne-kuchnie-na-wymiar-na-zamowienie-katowice-nowoczesne",
    name: "Meble kuchenne kuchnie na wymiar na zamówienie Katowice nowoczesne",
    city: "Katowice",
    voivodeship: "śląskie",
    website: "https://eternokuchnie.pl/",
    description: "Nasza - studia meblowego pod marką Eterno Kuchnie Katowice nowoczesne, klasyczne na Wymiar - niedawno się rozpoczęła. Wykorzystując wieloletnie rodzinne doświadczenie w branży stolarstwa i AGD, otworzyliśmy showroom w Katowicach- Meble kuchenne na zamówienie…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Sprzęt AGD", "Nowoczesne kuchnie", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.8,
  },
  {
    id: "katowice-meble-kuchenne-na-wymiar-katowice",
    name: "Meble kuchenne na wymiar Katowice",
    city: "Katowice",
    voivodeship: "śląskie",
    website: "https://stolarzkatowice.pl/meble-na-wymiar/kuchenne/",
    description: "Meble kuchenne na wymiar Katowice Marząc o nowoczesnej i funkcjonalnej kuchni, warto zastanowić się nad meblami kuchennymi na wymiar. W Katowicach znajdziesz szeroką ofertę, która pozwoli ci stworzyć kuchnię marzeń, idealnie dopasowaną do twoich potrzeb i…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.5,
  },
  {
    id: "katowice-meble-kuchenne-na-zamowienie-na-wymiar-krakow-meble-ernestrust",
    name: "Meble kuchenne na zamówienie - na wymiar - Kraków - Meble ernestrust",
    city: "Katowice",
    voivodeship: "śląskie",
    website: "https://rust.pl/kontakt/katowice/",
    description: "Showroom Katowice Zaaranżujemy dla Ciebie wymarzoną kuchnię! Produkując meble kuchenne w standardzie premium dbamy nie tylko o ich wytrzymałość, ergonomię i estetykę. Zależy nam na dopasowaniu do indywidualnych oczekiwań Klientów.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Klasyczne kuchnie"],
    rating: 4.9,
  },
  {
    id: "katowice-meble-na-wymiar-katowice-kuchnie-szafy-mahmann",
    name: "Meble na wymiar Katowice - kuchnie, szafy | Mahmann",
    city: "Katowice",
    voivodeship: "śląskie",
    website: "https://www.mahmann-meble.pl/",
    description: "Meble kuchenne na wymiar - od minimalistycznych, nowoczesnych układów z ukrytą funkcją, po klasyczne kompozycje z duszą; projektujemy kuchnie, które współgrają z rytmem codzienności.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Klasyczne kuchnie"],
    rating: 4.5,
  },
  {
    id: "katowice-kuchnie-katowice-meble-kuchenne-klasyczne-i-nowoczesne-slask-aranzacje",
    name: "kuchnie Katowice, meble kuchenne klasyczne i nowoczesne Śląsk - aranżacje",
    city: "Katowice",
    voivodeship: "śląskie",
    website: "http://www.slaskiekuchnie.pl/",
    description: "Oferujemy nowoczesne i klasyczne aranżacje kuchni. Gwarantujemy wysokiej jakości meble kuchenne . Zapraszamy do odwiedzenia naszego sklepu w Katowicach (Śląsk). Meble wysokiej jakości - Katowice , Śląsk!",
    services: ["Projektowanie", "Produkcja", "Montaż", "Sklep internetowy", "Nowoczesne kuchnie", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.4,
  },
  {
    id: "krakow-archidom-krakow-meble-kuchenne-kuchnie-na-wymiar-kuchnia-na",
    name: "Archidom Kraków - Meble Kuchenne. Kuchnie na wymiar, kuchnia na ...",
    city: "Kraków",
    voivodeship: "małopolskie",
    website: "https://meble-kuchenne-krakow.com.pl/",
    description: "Archidom. Meble kuchenne i kuchnie na wymiar. Archidom to nie tylko firma, to zespół doświadczonych specjalistów, dla których kuchnia to coś więcej niż zwykłe pomieszczenie. Dla nas, kuchnia to serce domu, miejsce pełne życia, wspomnień i ciepła, które wymaga…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.4,
  },
  {
    id: "krakow-archidom-krakow-meble-kuchenne-kuchnie-na-wymiar-zamowienie-producent",
    name: "Archidom Kraków - meble kuchenne kuchnie na wymiar zamówienie producent ...",
    city: "Kraków",
    voivodeship: "małopolskie",
    website: "https://archidom.com.pl/",
    description: "Archidom Kraków Kuchnie na wymiar Meble kuchenne na zamówienie ☎ +48 663 369 909 ☎ Zaufaj naszemu doświadczeniu w projektowaniu kuchni.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.7,
  },
  {
    id: "krakow-dla-ciebie-wszystko-krakow-w-kategorii-meble-kuchenne",
    name: "Dla Ciebie wszystko - Kraków - w kategorii Meble kuchenne",
    city: "Kraków",
    voivodeship: "małopolskie",
    website: "https://www.olx.pl/dom-ogrod/meble/meble-kuchenne/krakow/",
    description: "Skorzystaj z największego serwisu ogłoszeniowego - Kraków i okolice! - kupuj lub sprzedawaj jeszcze wygodniej w kategorii Meble kuchenne !",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.8,
  },
  {
    id: "krakow-fm-kuchnie-krakow-meble-kuchenne-kuchnie-na-wymiar",
    name: "FM KUCHNIE Kraków - Meble kuchenne, kuchnie na wymiar",
    city: "Kraków",
    voivodeship: "małopolskie",
    website: "https://www.kuchniewfm.com/",
    description: "Oferujemy kompleksowe zabudowy wnętrza kuchni. Meble kuchenne , kuchnie na wymiar w nowoczesnym i klasycznym wzornictwie. Zapraszamy do naszych salonów.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Zabudowy", "Nowoczesne kuchnie", "Klasyczne kuchnie"],
    rating: 4.7,
  },
  {
    id: "krakow-kuchnie-krakow-salon-sprzedazy-kuchni-na-wymiar-meble-halupczok",
    name: "Kuchnie Kraków - Salon sprzedaży kuchni na wymiar | Meble ... - HALUPCZOK",
    city: "Kraków",
    voivodeship: "małopolskie",
    website: "https://meble-halupczok.pl/salony-sprzedazy/kuchnie-krakow/",
    description: "MEBLE KUCHENNE KRAKÓW Meble kuchenne na wymiar Kraków to obecnie jeden z najnowszych showroom-ów marki Halupczok. Wyeksponowano tu kolekcje kuchni: Toscana - wysmakowany duet Valentia - indywidualizm loftowych klimatów Marrone - kojąca zmysłowość Eleganza -…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Klasyczne kuchnie"],
    rating: 4.7,
  },
  {
    id: "krakow-meble-kuchenne-na-wymiar-krakow-wycena-online",
    name: "Meble Kuchenne na Wymiar - Kraków Wycena Online",
    city: "Kraków",
    voivodeship: "małopolskie",
    website: "https://meble-kuchenne.krakow.pl/",
    description: "Te meble kuchenne w Krakowie łączą w sobie funkcjonalność i styl, tworząc przestrzeń idealną do gotowania i spotkań z rodziną. Kuchnie na wymiar Kraków pozwalają na pełną personalizację, od wyboru materiałów, przez kolorystykę, po układ mebli.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie"],
    rating: 4.7,
  },
  {
    id: "krakow-meble-kuchenne-krakow-kuchnie-na-wymiar-i-gotowe-zestawy",
    name: "Meble kuchenne Kraków - kuchnie na wymiar i gotowe zestawy",
    city: "Kraków",
    voivodeship: "małopolskie",
    website: "https://meblekuchenne.pl/meble-kuchenne-krakow/",
    description: "Meble kuchenne Kraków - Kompleksowe Rozwiązania Online i Sklep Internetowy Meble kuchenne na wymiar i gotowe zestawy - Kraków i okolice Zaprojektuj swoją wymarzoną kuchnię z łatwością, nie wychodząc z domu! Nasza oferta obejmuje zarówno indywidualne…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Sklep internetowy", "Nowoczesne kuchnie"],
    rating: 4.8,
  },
  {
    id: "krakow-meble-kuchenne-krakow-agata-agata-sklep-salony-agata",
    name: "Meble kuchenne Kraków | Agata - Agata Sklep - Salony Agata",
    city: "Kraków",
    voivodeship: "małopolskie",
    website: "https://www.agatameble.pl/sklep/krakow/meble-kuchenne",
    description: "W Krakowie meble kuchenne z włoskim sznytem, które prezentują się elegancko i nowocześnie, znajdziesz zarówno w rozbielonej tonacji, jak i w ciemniejszej kolorystyce. Od Ciebie zależy, czy zdecydujesz się na urządzenie wyrazistego pomieszczenia w…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.5,
  },
  {
    id: "krakow-meble-kuchenne-kuchnie-krakow",
    name: "Meble kuchenne, kuchnie Kraków",
    city: "Kraków",
    voivodeship: "małopolskie",
    website: "https://www.cholewameble.pl/",
    description: "Meble kuchenne kuchnie na wymiar Kraków Nasza oferta mebli kuchennych na wymiar to połączenie nowoczesności z klasyczną elegancją. Oferujemy szeroki wybór materiałów, kolorów i wykończeń, dzięki czemu każda kuchnia jest unikatowa i idealnie dopasowana do…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Klasyczne kuchnie"],
    rating: 4.5,
  },
  {
    id: "krakow-nowoczesne-meble-kuchenne-na-wymiar-meble-kuchenne-do-zabudowy-baum",
    name: "Nowoczesne meble kuchenne na wymiar | Meble kuchenne do zabudowy - Baum ...",
    city: "Kraków",
    voivodeship: "małopolskie",
    website: "https://baumcentrum.pl/",
    description: "Meble kuchenne - nowoczesne, klasyczne i minimalistyczne Kuchnie i meble na wymiar, które wykonujemy w naszej krakowskiej pracowni to nasza specjalność. Do każdego klienta zawsze podchodzimy w sposób indywidualny i dokładamy starań, aby sprostać nawet…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.5,
  },
  {
    id: "lublin-format-meble-kuchenne-lublin",
    name: "Format - Meble kuchenne Lublin",
    city: "Lublin",
    voivodeship: "lubelskie",
    website: "http://meblekuchenneformat.pl/",
    description: "Każdorazowo meble kuchenne tworzone są na wymiar, projektowane są według życzeń i upodobań klienta, z uwzględnieniem indywidualnych potrzeb. Firma FORMAT swoje meble przemyślała tak, aby każdy klient znalazł tu coś dla siebie, niezależnie od kwoty jaką chce…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.9,
  },
  {
    id: "lublin-kuchnie-lublin-kuchnie-i-agd-pracownia-kr",
    name: "Kuchnie Lublin | Kuchnie i AGD Pracownia KR",
    city: "Lublin",
    voivodeship: "lubelskie",
    website: "https://pracowniakr.pl/",
    description: "Jesteśmy studiem topowych producentów mebli kuchennych Atlas Kuchnie oraz Häcker. Wierzymy, że kuchnia - jako serce domu - to przestrzeń, która zasługuje na najwyższą jakość. Jeśli interesują Cię meble kuchenne na wymiar w Lublinie i okolicy, przyjdź do…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.5,
  },
  {
    id: "lublin-kuchnie-i-meble-kuchenne-lublin-tomasz-meble-kuchenne-niemieckie",
    name: "Kuchnie i meble kuchenne Lublin | Tomasz Meble Kuchenne niemieckie",
    city: "Lublin",
    voivodeship: "lubelskie",
    website: "https://www.tomaszkuchnielublin.pl/",
    description: "Firma Tomasz Meble kuchenne z Lublina odmieni Twoja kuchnie! Tylko u nas znajdziesz meble kuchenne wysokiej jakości w tak niskiej cenie! Zapraszamy!",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.3,
  },
  {
    id: "lublin-meble-kuchenne-centrum-meblowe-wokulski-lublin",
    name: "Meble Kuchenne - Centrum Meblowe \"Wokulski Lublin",
    city: "Lublin",
    voivodeship: "lubelskie",
    website: "https://www.wokulski.lublin.pl/product-category/meble-kuchenne",
    description: "Meble kuchenne w Centrum Meblowe \"Wokulski\" Lublin , ul. Łęczyńska 5. Oferta 50 producentów mebli m.in.: ATM SOFA, CAYA DESIGN, ETAP SOFA, MEBLE WÓJCIK",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.4,
  },
  {
    id: "lublin-meble-kuchenne-lublin-kuchnie-na-wymiar-w-najlepszej-jakosci",
    name: "Meble kuchenne Lublin - kuchnie na wymiar w najlepszej jakości",
    city: "Lublin",
    voivodeship: "lubelskie",
    website: "https://meblekuchenne.pl/meble-kuchenne-lublin/",
    description: "Meble kuchenne w Lublinie - projektujemy kuchnie na wymiar, dopasowane do Twoich potrzeb. Wysoka jakość, funkcjonalność i estetyka w jednym!",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie"],
    rating: 4.4,
  },
  {
    id: "lublin-meble-kuchenne-lublin-kuchnie-szafy-pph-g-bora",
    name: "Meble kuchenne Lublin, kuchnie, szafy - PPH G-Bora",
    city: "Lublin",
    voivodeship: "lubelskie",
    website: "http://meble-gbora.pl/",
    description: "PPH G-Bora Lublin od 1991 roku realizuje zamówienia na meble kuchenne , szafy, garderoby, kuchnie drewniane, meble biurowe i gabinetowe oraz meble tapicerowane.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Klasyczne kuchnie"],
    rating: 4.5,
  },
  {
    id: "lublin-meble-kuchenne-na-wymiar-lublin-3top-kuchnie",
    name: "Meble kuchenne na wymiar Lublin | 3TOP Kuchnie",
    city: "Lublin",
    voivodeship: "lubelskie",
    website: "https://3top.pl/nasze-salony/salon-lublin",
    description: "Możemy bez problemu dopasować meble kuchenne na wymiar, ale także do wybranego designu mieszkania. 3TOP Meble kuchenne - Lublin Pozostajemy do dyspozycji tych z Państwa, dla których priorytetem jest przygotowanie aranżacji kuchni w pełni dopasowanej do…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.3,
  },
  {
    id: "lublin-meble-kuchenne-na-wymiar-i-zamowienie-lublin-kuchnie-tukan",
    name: "Meble kuchenne na wymiar i zamówienie Lublin - Kuchnie Tukan",
    city: "Lublin",
    voivodeship: "lubelskie",
    website: "https://mebletukan.pl/",
    description: "Kuchnie Tukan Lublin ⭐ Tworzymy meble meble kuchenne na wymiar i zamówienie ⭐ idealne do każdego wnętrza! Zachwycający design i funkcjonalność. Sprawdź!",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.7,
  },
  {
    id: "lublin-meble-na-wymiar-lublin-mebelek-meble-na-zamowienie",
    name: "Meble na wymiar Lublin | Mebelek | meble na zamówienie",
    city: "Lublin",
    voivodeship: "lubelskie",
    website: "https://mebelek-lublin.pl/",
    description: "Od lat zajmujemy się produkcją mebli na zamówienie: meble kuchenne , szafy przesuwne, garderoby, kuchnie do zabudowy, meble pod wymiar",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Klasyczne kuchnie"],
    rating: 4.9,
  },
  {
    id: "lublin-salon-mebli-kuchennych-oraz-azienkowych-credo-w-lublinie",
    name: "Salon mebli kuchennych oraz łazienkowych Credo w Lublinie",
    city: "Lublin",
    voivodeship: "lubelskie",
    website: "https://www.credokuchnie.pl/",
    description: "Salon mebli kuchennych Credo w Lublinie Salon mebli kuchennych Credo zlokalizowany jest w Lublinie, przy ul. Fabrycznej, na terenie Galerii Gala. W naszym studio znajdziesz wysokiej jakości szafki kuchenne oraz łazienkowe firmy Verle Küchen. Jesteśmy bowiem…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Zabudowy", "Nowoczesne kuchnie"],
    rating: 4.9,
  },
  {
    id: "poznan-meble-i-kuchnie-na-wymiar-poznan-klm",
    name: "Meble i Kuchnie na Wymiar Poznań | KLM",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    website: "https://meble-poznan.com.pl/meble-kuchenne-na-wymiar/",
    description: "KUCHNIE NA WYMIAR POZNA Ń KLM to producent mebli z miasta Pozna ń, którego specjalizacją są nowoczesne kuchnie na wymiar i wszelkiego rodzaju meble kuchenne . Jesteśmy ekspertami w dziedzinie mebli do kuchni, oferując szeroką gamę produktów, takich jak:…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.8,
  },
  {
    id: "poznan-meble-kuchenne-poznan-kuchnie-na-wymiar-na-zamowienie-villa-project",
    name: "Meble kuchenne Poznań - kuchnie na wymiar na zamówienie | Villa Project",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    website: "https://www.villaproject.pl/",
    description: "Najlepsze meble kuchenne w Poznaniu ⭐ Wybierz kuchnie na wymiar z Villa Project Odwiedź studio mebli kuchennych - Pozna ń!",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Nowoczesne kuchnie"],
    rating: 4.8,
  },
  {
    id: "poznan-meble-kuchenne-poznan-kuchnie-nowoczesne-klasyczne-niemieckie-na",
    name: "Meble kuchenne Poznań - kuchnie nowoczesne, klasyczne, niemieckie - na ...",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    website: "https://i-kuchnie.pl/",
    description: "Studio DECCO kuchnie oferuje projektowanie, wykonanie i montaż mebli kuchennych na wymiar. Nowoczesne, klasyczne, niemieckie, skandynawskie, prowansalskie - u nas wybierzesz kuchnię dla siebie!",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Nowoczesne kuchnie", "Klasyczne kuchnie"],
    rating: 4.5,
  },
  {
    id: "poznan-meble-kuchenne-poznan-agata-agata-sklep-salony-agata",
    name: "Meble kuchenne Poznań | Agata - Agata Sklep - Salony Agata",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    website: "https://www.agatameble.pl/sklep/poznan/meble-kuchenne",
    description: "Uniwersalne meble kuchenne w Poznaniu Ekskluzywne meble kuchenne w Poznaniu cieszą się dużą popularnością wśród mieszkańców tego dynamicznie rozwijającego się miasta. W sklepie Agata klienci znajdują wyposażenie, które odpowiada na wyzwania współczesnego…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Sklep internetowy", "Nowoczesne kuchnie"],
    rating: 4.6,
  },
  {
    id: "poznan-meble-kuchenne-poznan-kuchnie-swarzedz-lubon-projektowanie-kuchni",
    name: "Meble kuchenne Poznań, kuchnie Swarzędz, Luboń, projektowanie kuchni",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    website: "https://koncept2m.pl/",
    description: "Studio mebli kuchennych w Poznaniu Dąbrowskiego 109. Projektujemy i wykonujemy meble z najwyższą precyzją - jak przystało na niemieckie kuchnie. Zajrzyj!",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Klasyczne kuchnie"],
    rating: 4.9,
  },
  {
    id: "poznan-meble-kuchenne-poznan-kuchnie-poznan-meble-kuchenne-na-wymiar-poznan",
    name: "Meble kuchenne Poznań, kuchnie poznań, meble kuchenne na wymiar poznań ...",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    website: "https://niemieckie-meble.pl/",
    description: "Meble kuchenne Nobilia meble kuchenne pozna ń Witamy! Meble kuchenne to nasza pasja Doświadczenie, otwartość na potrzeby Klientów oraz fachowy montaż - oto główne zalety będące wizytówką salonów Art Design. Niemieckie meble kuchenne Nobilia produkowane są w…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.6,
  },
  {
    id: "poznan-meble-kuchenne-kuchnie-na-wymiar-zamowienie-puciennik-poznan",
    name: "Meble kuchenne kuchnie na wymiar zamówienie Płuciennik Poznań",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    website: "https://pluciennik.pl/",
    description: "Firma Płuciennik to rodzinna stolarnia z Wielkopolski, która od 1974 roku tworzy meble najwyższej jakości. Nasza historia zaczęła się od małego warsztatu, gdzie zajmowaliśmy się renowacją mebli stylowych, a dziś jesteśmy renomowanym producentem mebli na…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.4,
  },
  {
    id: "poznan-meble-kuchenne-na-zamowienie-na-wymiar-poznan-meble-ernestrust",
    name: "Meble kuchenne na zamówienie - na wymiar - Poznań - Meble ernestrust",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    website: "https://rust.pl/kontakt/poznan/",
    description: "Nasi projektanci wezmą wszystkie te elementy pod uwagę, przygotowując meble na wymiar i dobierając najciekawszą koncepcję wizualną, wykorzystując do tego nowatorskie technologie i najlepsze jakościowo materiały.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.6,
  },
  {
    id: "poznan-zwymiarowani-meble-kuchenne-na-wymiar-poznan-kuchnie-na-zamowienie-w",
    name: "Zwymiarowani - meble kuchenne na wymiar Poznań, kuchnie na zamówienie w ...",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    website: "https://zwymiarowani.pl/",
    description: "Zwymiarowani - meble kuchenne na wymiar Pozna ń, kuchnie na zamówienie w Poznaniu. Projektowanie mebli do kuchni - wizualizacja aranżacja projekt. Zabudowa kuchenna, solidna nowoczesna luksusowa elegancka loftowa kuchnia premium w dobrej cenie. Indywidualna…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Nowoczesne kuchnie", "Wizualizacje 3D", "Bezpłatna wycena"],
    rating: 4.8,
  },
  {
    id: "poznan-meble-kuchenne-na-zamowienie-poznan-culina3d",
    name: "meble kuchenne na zamówienie Poznań - Culina3d",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    website: "https://culina3d.pl/poznan/",
    description: "Meble kuchenne na zamówienie Poznań to po prostu meble , które zostały zaprojektowane i wykonane specjalnie dla Państwa według wcześniej ustalonych oczekiwań i wizji. Oznacza to, że zostaną one wykonane na wymiar, dzięki czemu będą idealnie pasować do danej…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.8,
  },
  {
    id: "szczecin-kuchnie-na-wymiar-szczecin-expert-meble",
    name: "Kuchnie na wymiar Szczecin - Expert Meble",
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
    website: "https://expertmeble.com/kuchnie-na-wymiar/",
    description: "Meble kuchenne na wymiar, które otrzymacie będą wykonane z materiałów najwyższej jakości, oraz przybiorą styl waszych marzeń (nowoczesny, klasyczny oraz inne). Każdą kuchnię na wymiar wyposażamy również we wszystkie niezbędne elementy według życzeń…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Klasyczne kuchnie"],
    rating: 4.6,
  },
  {
    id: "szczecin-meble-serpe-salon-meblowy-szczecin",
    name: "Meble Serpe - Salon Meblowy Szczecin",
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
    website: "https://serpe.pl/",
    description: "Serpe Meble Szczecin oferuje meble kuchenne nowoczesne i klasyczne. Kuchnie na wymiar są podstawą naszej oferty, dzięki czemu każdy klient może urządzić nawet najbardziej nietypowe pomieszczenie. Indywidualny projekt, wizualizację i wycenę wykonujemy w Naszym…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Klasyczne kuchnie", "Wizualizacje 3D", "Bezpłatna wycena"],
    rating: 4.4,
  },
  {
    id: "szczecin-meble-kuchenne-salon-meblowy-w-szczecinie-duzy-wybor-mebli-aba",
    name: "Meble kuchenne - Salon meblowy w Szczecinie, duży wybór mebli | Aba ...",
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
    website: "http://www.aba-meble.pl/oferta/meble-kuchenne.html",
    description: "ABA Meble Szczecin - Salon meblowy w Szczecinie. Posiadamy szeroką gamę mebli do wyposażenia mieszkania i domu. Dysponujemy przestrzenią wystawową umożliwiającą Klientom obejrzenie mebli. Oferujemy również zamówienie zestawy mebli kuchennych na wymiar.…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Nowoczesne kuchnie"],
    rating: 4.8,
  },
  {
    id: "szczecin-meble-kuchenne-swiat-mebli-szczecin-salon-meblowy",
    name: "Meble kuchenne - Świat Mebli Szczecin - Salon Meblowy",
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
    website: "http://www.swiatmebli.szczecin.pl/kategoria/kuchnia/",
    description: "Meble do kuchni Kuchnia to jedno z najważniejszych pomieszczeń w domu. To nie tylko miejsce przygotowywania posiłków, lecz także często spotkań i spędzania czasu z rodziną. Warto więc zadbać, aby było ono wyjątkowe. Dzięki naszej ofercie możesz zaplanować…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.4,
  },
  {
    id: "szczecin-meble-kuchenne-szczecin-kuchnie-na-wymiar-w-najlepszym-stylu",
    name: "Meble kuchenne Szczecin - kuchnie na wymiar w najlepszym stylu",
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
    website: "https://meblekuchenne.pl/meble-kuchenne-szczecin/",
    description: "Meble kuchenne w Szczecinie - projektujemy kuchnie na wymiar, które łączą elegancję z funkcjonalnością. Stwórz z nami swoją wymarzoną kuchnię!",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.6,
  },
  {
    id: "szczecin-meble-kuchenne-na-wymiar-szczecin-kuchnie-na-wymiar",
    name: "Meble kuchenne na wymiar - Szczecin - Kuchnie na wymiar",
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
    website: "https://darex-kuchnie.pl/",
    description: "Jak zamówić meble kuchenne Szczecin ? Proces zamawiania mebli kuchennych na wymiar z Darex jest prosty i przejrzysty. Poniżej przedstawiamy, w jaki sposób realizujemy meble kuchenne na zamówienie, z omówieniem poszczególnych etapów, aby dać Ci pełne…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.9,
  },
  {
    id: "szczecin-meble-kuchenne-na-wymiar-szczecin-stolarz-micha-kaczanowski",
    name: "Meble kuchenne na wymiar Szczecin - Stolarz Michał Kaczanowski",
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
    website: "https://meble-szczecin.com/oferta/meble-kuchenne/",
    description: "Meble kuchenne Szczecin i okolice Nasza firma specjalizuje się w produkcji wysokiej jakości mebli kuchennych na wymiar, a także innego wyposażenia dla Twojego domu czy mieszkania.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie"],
    rating: 4.5,
  },
  {
    id: "szczecin-meble-na-wymiar-szczecin-kuchnie-pod-zabudowe-house4design",
    name: "Meble na wymiar Szczecin - Kuchnie pod zabudowe - House4Design",
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
    website: "https://www.house4design.com/",
    description: "Oferujemy meble na wymiar o różnym przeznaczeniu i różnej stylistyce. Długoletnie doświadczenie pozwala nam na zajęcie pozycji lidera wśród salonów kuchennych w mieście Szczecin . Jeśli chodzi o meble kuchenne na wymiar to dajemy Państwu możliwość wyboru…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.4,
  },
  {
    id: "szczecin-meble-na-zamowienie-kuchenne-azienkowe-do-salonu-agal",
    name: "Meble na zamówienie: kuchenne, łazienkowe, do salonu | AGAL",
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
    website: "https://www.agal.pl/",
    description: "Od wielu lat produkujemy niepowtarzalne meble kuchenne , łazienkowe, biurowe i do salonu na zamówienie. Wytwarzamy garderoby, blaty, szafki RTV, zabudowy do kuchni, szafy przesuwne na wymiar i inne. Działamy na terenie Szczecina i okolic.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Zabudowy", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.9,
  },
  {
    id: "szczecin-studio-mebli-kuchennych-virgo-kuchnie-szczecin",
    name: "Studio mebli kuchennych Virgo kuchnie Szczecin",
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
    website: "https://www.virgostudio.pl/",
    description: "KUCHNIE SZCZECIN - MISJA VIRGO STUDIO Naszą misją jest jakość i zadowolenie klienta dlatego jesteśmy dystrybutorem marek Nobilia Kuchnie i Sachsen Kuechen, które dostarczają kuchnie od 76 lat i ponad 100 lat. Bazując na tradycji i olbrzymim doświadczeniu obu…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.7,
  },
  {
    id: "warszawa-artii-meble-kuchenne-warszawa",
    name: "Artii - Meble kuchenne Warszawa",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    website: "https://www.kuchnie-artii.pl/",
    description: "Oferujemy Państwu najwyższej jakości meble kuchenne robione na wymiar, oraz sprzęt AGD. Do każdego projektu podchodzimy indywidualnie, starając się zawsze w pełni poznać potrzeby naszego Klienta.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Sprzęt AGD", "Nowoczesne kuchnie"],
    rating: 4.7,
  },
  {
    id: "warszawa-interio-meble-kuchenne-na-zamowienie-kuchnie-nolte-warszawa",
    name: "Interio - Meble kuchenne na zamówienie - Kuchnie Nolte Warszawa",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    website: "https://interio-meble.pl/",
    description: "Meble kuchenne Nolte Warszawa Kuchnie niemieckie Największa sieć salonów Nolte Ponad 20 lat współpracy z NOLTE KUCHEN HOME CONCEPT CH JUPITER DOMOTEKA",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.4,
  },
  {
    id: "warszawa-karant-meble-kuchenne-na-zamowienie-kuchnie-szafy-warszawa",
    name: "KARANT Meble kuchenne na zamówienie kuchnie szafy Warszawa",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    website: "https://karant.pl/",
    description: "Kuchnie, meble kuchenne Warszawa Meble kuchenne to nasza specjalność, projektujemy je i wykonujemy od ponad 27 lat. Ponadto realizujemy różnego rodzaju zabudowy garderób, przedpokoje, szafy, meble do łazienek oraz inne meble na zamówienie. Zapraszamy do…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Nowoczesne kuchnie"],
    rating: 4.3,
  },
  {
    id: "warszawa-kuchnie-nolte-warszawa-najwiekszy-salon-w-polsce",
    name: "Kuchnie Nolte Warszawa - Największy Salon w Polsce",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    website: "https://www.noltekuchen.pl/",
    description: "Otrzymaja Panstwo swietny spersonalizowany projekt, bardzo dobrej jakosci meble i najlepsza obsluge klienta. Bardzo dziękujemy Pani Oldze i calemu zespolowi za nasza piekna kuchnie z wyspa 🤩💚 i pozdrawiamy serdecznie. Ps. Lodowka Liebheerr jest rewelacyjna.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.4,
  },
  {
    id: "warszawa-meble-kuchenne-warszawa-nowoczesne-kuchnie-na-wymiar",
    name: "Meble Kuchenne Warszawa - Nowoczesne Kuchnie na Wymiar",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    website: "https://meblekuchenne.pl/meble-kuchenne-warszawa/",
    description: "Meble kuchenne Warszawa - Zaprojektuj swoją wymarzoną kuchnię z łatwością, nie wychodząc z domu! Nasza oferta obejmuje zarówno indywidualne projektowanie kuchni na wymiar, jak i sprzedaż gotowych zestawów mebli kuchennych w sklepie internetowym.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Sklep internetowy", "Nowoczesne kuchnie"],
    rating: 4.4,
  },
  {
    id: "warszawa-meble-kuchenne-warszawa-na-wymiar-kuchnie-ams",
    name: "Meble Kuchenne Warszawa na Wymiar - Kuchnie AMS",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    website: "https://amsmeble.pl/",
    description: "Korzystamy z nowoczesnych technologii w produkcji mebli kuchennych. Staramy się utrzymać wysoki standard wykonania kuchni na wymiar Warszawa .",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.4,
  },
  {
    id: "warszawa-meble-kuchenne-i-kuchnie-na-wymiar-warszawa",
    name: "Meble Kuchenne i Kuchnie na Wymiar - Warszawa",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    website: "https://meble-kuchenne.warszawa.pl/",
    description: "Kuchnie Warszawa - Projektowane na Wymiar Chcesz mieć meble kuchenne na wymiar? Zrealizujemy dla Ciebie każdy projekt kuchni i nie tylko. Obsługujemy klientów z Warszawy oraz okolic miasta. Realizujemy zamówienia na terenie województwa mazowieckiego.…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.5,
  },
  {
    id: "warszawa-meble-kuchenne-warszawa",
    name: "Meble kuchenne Warszawa",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    website: "https://www.romameble.pl/",
    description: "Jesteśmy firmą z 20 letnim doświadczeniem. Produkujemy meble kuchenne Warszawa , blaty kamienne Warszawa , meble na wymiar Warszawa , . Nasi specjaliści pomogą Ci w doborze odpowiednich materiałów, wzorów i kolorów uwzględniając przy tym Twoje sugestie jak i…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.7,
  },
  {
    id: "warszawa-meble-kuchenne-na-zamowienie-na-wymiar-warszawa-meble-ernestrust",
    name: "Meble kuchenne na zamówienie - na wymiar - Warszawa - Meble ernestrust",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    website: "https://rust.pl/kontakt/warszawa/",
    description: "Meble kuchenne Warszawa u2028studio ernestrust Przekonaj się, że marzenia są naprawdę na wyciągnięcie ręki. Idealna kuchnia na wymiar może powstać, gdy tylko zdecydujesz się odwiedzić nasz salon wnętrz w stolicy lub w Jankach koło Warszawy.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Klasyczne kuchnie"],
    rating: 4.7,
  },
  {
    id: "warszawa-meble-warszawa-meble-kuchenne-warszawa-projekty-kuchni-jbw-meble",
    name: "Meble warszawa, meble kuchenne warszawa, projekty kuchni, JBW Meble ...",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    website: "http://www.jbwmeble.pl/",
    description: "W naszej ofercie znajdziecie Państwo meble kuchenne wraz ze sprzętem AGD, szafy wnękowe, szafy wolnostojące, garderoby, meble łazienkowe oraz inne nietypowe zabudowy .",
    services: ["Projektowanie", "Produkcja", "Montaż", "Sprzęt AGD", "Zabudowy", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.5,
  },
  {
    id: "wrocaw-dj-meble-meble-kuchenne-wrocaw-producent-mebli-na-wymiar",
    name: "DJ Meble. Meble kuchenne Wrocław. Producent mebli na wymiar ...",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    website: "https://meble-dj.pl/",
    description: "MEBLE KUCHENNE Oferujemy meble kuchenne na wymiar Wrocław i okolice. Biorąc pod uwagę wymagania i oczekiwania Klienta proponujemy rozwiązania cechujące się dużą funkcjonalnością i elegancją. W naszych kuchniach wykorzystujemy akcesoria wiodących producentów…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie"],
    rating: 4.8,
  },
  {
    id: "wrocaw-kuchnie-na-wymiar-wrocaw-meble-kuchenne",
    name: "Kuchnie na Wymiar Wrocław - Meble Kuchenne",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    website: "https://meble-kuchenne.wroclaw.pl/",
    description: "Meble Kuchenne i Kuchnie na Wymiar ☝ Wrocław . Pracujemy na terenie Wrocławia ⭐ Ceny Producenta ⭐ Sprawdź! ☎️ 512-585-275.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.7,
  },
  {
    id: "wrocaw-kuchnie-na-wymiar-wrocaw-meble-kuchenne-na-zamowienie-meble-drzazga",
    name: "Kuchnie na wymiar Wrocław, Meble kuchenne na zamówienie - Meble Drzazga ...",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    website: "https://mebledrzazga.pl/",
    description: "Tworzymy nowoczesne i klasyczne kuchnie na wymiar i meble kuchenne . 35 lat na rynku we Wrocławiu. Zaufaj firmie z doświadczeniem!",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.7,
  },
  {
    id: "wrocaw-meble-kuchenne-wrocaw-studio-mebli-kuchennych-marek-sobczak",
    name: "Meble kuchenne Wrocław - Studio Mebli Kuchennych Marek Sobczak",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    website: "https://meblekuchennewroclaw.pl/",
    description: "STUDIO MEBLI KUCHENNYCH SOBCZAK we Wrocławiu to meble kuchenne wysokiej jakości. Montażem mebli kuchennych, szaf na wymiar i mebli łazienkowych na terenie miasta Wrocławia.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Zabudowy", "Klasyczne kuchnie"],
    rating: 4.6,
  },
  {
    id: "wrocaw-meble-kuchenne-wrocaw-kuchnie-na-wymiar-i-gotowe-zestawy",
    name: "Meble kuchenne Wrocław - kuchnie na wymiar i gotowe zestawy",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    website: "https://meblekuchenne.pl/meble-kuchenne-wroclaw/",
    description: "Meble kuchenne Wrocław - Kompleksowe Rozwiązania Online i Sklep Internetowy Meble kuchenne na wymiar i gotowe zestawy - Wrocław i okolice Zaprojektuj swoją wymarzoną kuchnię z łatwością, nie wychodząc z domu! Nasza oferta obejmuje zarówno indywidualne…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Sklep internetowy", "Klasyczne kuchnie"],
    rating: 4.5,
  },
  {
    id: "wrocaw-meble-kuchenne-wrocaw-meble-na-wymiar-kuchnie-na-zamowienie",
    name: "Meble kuchenne Wrocław | Meble na wymiar | Kuchnie na zamówienie",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    website: "https://www.kuchenni.pl/",
    description: "Wykonujemy meble na wymiar we Wrocławiu i okolicach. W ofercie posiadamy meble kuchenne , szafy, meble łazienkowe, garderoby. Profesjonalne doradztwo i montaż.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Klasyczne kuchnie"],
    rating: 4.9,
  },
  {
    id: "wrocaw-meble-na-wymiar-wrocaw-kuchnie-na-zamowienie-meble-kosinscy",
    name: "Meble na wymiar Wrocław - kuchnie na zamówienie - Meble Kłosińscy",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    website: "https://mebleklosinscy.pl/",
    description: "Dzięki temu, nasze meble kuchenne na wymiar są nie tylko piękne, ale także trwałe i odporne na uszkodzenia. Warto zaznaczyć, że Meble Kłosińscy to firma lokalna, działająca na rynku meblarskim od wielu lat. Nasze meble na wymiar oraz kuchnie na zamówienie…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.6,
  },
  {
    id: "wrocaw-proarte-kuchnie-na-wymiar-meble-na-wymiar-we-wrocawiu-meble",
    name: "ProArte Kuchnie na wymiar Meble na wymiar we Wrocławiu. Meble",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    website: "https://proartemeble.pl/",
    description: "Zabudowa wnęk Wrocław . Nowoczesne meble kuchenne . Projektowanie wnętrz. Szafy na wymiar. Meble łazienkowe na wymiar. Producent mebli na zamówienie. Meble do sypialni na wymiar. Kompleksowa aranżacja wnętrz. Projektowanie kuchni. Projektowanie szaf. Stolarz…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Nowoczesne kuchnie"],
    rating: 4.7,
  },
  {
    id: "wrocaw-rik-meble-kuchenne-wrocaw-szafy-wnekowe-meble-azienkowe-strona-gowna",
    name: "RIK Meble KUCHENNE Wrocław szafy wnękowe meble łazienkowe Strona Główna ...",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    website: "http://rikmeble.pl/",
    description: "Meble kuchenne Szafy Garderoby Meble Łazienkowe Meble Biurowe Meble Pokojowe Zapewniamy profesjonalne doradztwo w zakresie projektowania mebli. Indywidualne podejście do każdego klienta - na podstawie wywiadu przygotowujemy projekt wraz z wizualizacją oraz…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Nowoczesne kuchnie", "Wizualizacje 3D"],
    rating: 4.5,
  },
  {
    id: "wrocaw-strona-gowna-kuchnie-na-wymiar-wrocaw-meble-kuchenne-azienkowe",
    name: "Strona główna - Kuchnie na wymiar Wrocław - meble kuchenne, łazienkowe ...",
    city: "Wrocław",
    voivodeship: "dolnośląskie",
    website: "https://meble.in/",
    description: "Idealnie wpasowane WYKONUJEMY MEBLE NA WYMIAR Nasza dewiza to solidne meble , w przystępnej cenie. Działamy na terenie Wrocławia oraz Krakowa i okolic. Darmowe pomiary i wycena Bezpłatne pomiary, konsultacje oraz wycena. Wykonujemy zarówno kuchnie budżetowe,…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.7,
  },
  {
    id: "odz-abc-macisz-odz-producent-mebli-na-wymiar",
    name: "ABC Macisz Łódź - producent mebli na wymiar",
    city: "Łódź",
    voivodeship: "łódzkie",
    website: "https://abc-macisz.pl/",
    description: "ABC Macisz Łódź to doświadczony od 20 lat producent mebli. Wykonuje kuchnie, meble kuchenne na wymiar, szafy przesuwne i wnękowe na indywidualne zamówienie.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Klasyczne kuchnie"],
    rating: 4.3,
  },
  {
    id: "odz-amadeusz-studio-mebli-kuchennych-odz",
    name: "Amadeusz - Studio mebli kuchennych - Łódź",
    city: "Łódź",
    voivodeship: "łódzkie",
    website: "http://studioamadeusz.pl/",
    description: "Historia Firma Amadeusz powstała w 1996 roku. Byliśmy jednym z pierwszych studiów mebli kuchennych w Łodzi. Początkowo w naszej ofercie znajdowały się meble kuchenne . Z czasem poszerzyliśmy ofertę o meble łazienkowe, pokojowe i szafy. Nasze produkty spotkały…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Nowoczesne kuchnie"],
    rating: 4.4,
  },
  {
    id: "odz-ambroziak-meble-studio-mebli-kuchennych-meble-kuchenne-odz",
    name: "Ambroziak Meble - Studio Mebli Kuchennych - Meble kuchenne Łódź ...",
    city: "Łódź",
    voivodeship: "łódzkie",
    website: "http://ambroziakmeble.pl/",
    description: "O firmie Jesteśmy firmą z tradycjami produkującą i projektującą meble kuchenne , pokojowe jak i biurowe. Dbamy o zadowolenie naszych klientów poprzez użycie zawsze najlepszej jakości materiałów. Wypełniamy wnętrze meblami na dowolny wymiar podany przez…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.5,
  },
  {
    id: "odz-dobry-styl-sek-kuchnie-salon-mebli-i-studio-kuchni-na-wymiar",
    name: "Dobry Styl & SEK Kuchnie - Salon mebli i studio kuchni na wymiar.",
    city: "Łódź",
    voivodeship: "łódzkie",
    website: "https://dobrystyl.net.pl/",
    description: "500 m2 przestrzeni wystawowej na której znajdą Państwo wysokiej klasy meble oraz dodatki dla domu, a także studio mebli kuchennych na wymiar w Łodzi.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Salon ekspozycyjny", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.4,
  },
  {
    id: "odz-kuchnia-na-wymiar-odz-meble-szafki-zabudowy-kuchenne-na-wymiar",
    name: "Kuchnia na wymiar Łódź - Meble, szafki, zabudowy kuchenne na wymiar ...",
    city: "Łódź",
    voivodeship: "łódzkie",
    website: "http://www.strefakuchni.pl/",
    description: "Kuchnia na wymiar Łódź - zabudowa, szafki i meble kuchenne na wymiar Oferujemy projektowanie i wykonanie kuchni na wymiar na terenie Łodzi i okolic.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Nowoczesne kuchnie"],
    rating: 4.4,
  },
  {
    id: "odz-kuchnie-na-zamowienie-meble-kuchenne-na-wymiar-odz-producent-mebli",
    name: "Kuchnie na zamówienie - meble kuchenne na wymiar łódź | Producent mebli ...",
    city: "Łódź",
    voivodeship: "łódzkie",
    website: "https://askuchnie.pl/",
    description: "Meble kuchenne oferowane przez naszą firmę na terenie miasta Łódź mogą być wykonane pod indywidualnie zamówiony wymiar. Dzięki takiemu rozwiązaniu kupujący otrzyma zestaw mebli nie tylko pasujących do siebie, ale także do miejsca, w którym chce, aby zostały…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie"],
    rating: 4.9,
  },
  {
    id: "odz-kuchnie-odz-meble-kuchenne-i-kuchnie-na-wymiar",
    name: "Kuchnie Łódź - Meble Kuchenne i Kuchnie na Wymiar",
    city: "Łódź",
    voivodeship: "łódzkie",
    website: "https://kuchnie.lodz.pl/",
    description: "Kuchnie na Wymiar Łódź Meble Kuchenne ☝ Produkcja Mebli Łódź i okolice ⭐ Najlepsze Ceny ⭐ Prosto od Producenta Sprawdź! ☎️ 512-585-275.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Nowoczesne kuchnie"],
    rating: 4.8,
  },
  {
    id: "odz-linea-studio-kuchni-meble-kuchenne-na-wymiar-aranzacje-kuchni-odz",
    name: "Linea Studio Kuchni Meble kuchenne na wymiar, aranżacje kuchni Łódź",
    city: "Łódź",
    voivodeship: "łódzkie",
    website: "http://lineastudiokuchni.pl/",
    description: "15 lat doświadczenia w produkcji i aranżacji: meble kucjenne, szafy wnękowe i garderoby. Realizujemy nietypowe meble na wymiar oraz na zamówienie w Łodzi.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Zabudowy", "Nowoczesne kuchnie", "Bezpłatna wycena"],
    rating: 4.3,
  },
  {
    id: "odz-meble-kuchenne-lukasso-meble",
    name: "Meble Kuchenne - Lukasso Meble",
    city: "Łódź",
    voivodeship: "łódzkie",
    website: "https://lukasso-meble.pl/meble-kuchenne/",
    description: "Wszystkie nasze meble kuchenne są projektowane z myślą o trwałości, komforcie użytkowania oraz ponadczasowym designie. Materiały najwyższej jakości - meble kuchenne Łódź Stosujemy wyłącznie sprawdzone materiały renomowanych producentów, takich jak Egger,…",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena"],
    rating: 4.6,
  },
  {
    id: "odz-meble-kuchenne-na-wymiar-odz-kuchnie-tercet",
    name: "Meble kuchenne na wymiar Łódź - Kuchnie Tercet",
    city: "Łódź",
    voivodeship: "łódzkie",
    website: "http://tercetmeble.pl/",
    description: "Meble kuchenne (kuchnie) na wymiar, zamówienie - Łódź Jesteśmy firmą działającą w branży meblarskiej nieprzerwanie od 1997 roku. Naszym Klientom oferujemy wysokiej jakości meble na wymiar.",
    services: ["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie"],
    rating: 4.6,
  },
] as const;

export const cityFilters = [
  {
    city: "Bydgoszcz",
    voivodeship: "kujawsko-pomorskie",
  },
  {
    city: "Gdańsk",
    voivodeship: "pomorskie",
  },
  {
    city: "Katowice",
    voivodeship: "śląskie",
  },
  {
    city: "Kraków",
    voivodeship: "małopolskie",
  },
  {
    city: "Lublin",
    voivodeship: "lubelskie",
  },
  {
    city: "Poznań",
    voivodeship: "wielkopolskie",
  },
  {
    city: "Szczecin",
    voivodeship: "zachodniopomorskie",
  },
  {
    city: "Warszawa",
    voivodeship: "mazowieckie",
  },
  {
    city: "Wrocław",
    voivodeship: "dolnośląskie",
  },
  {
    city: "Łódź",
    voivodeship: "łódzkie",
  },
] as const;

export const serviceFilters = 
["Projektowanie", "Produkcja", "Montaż", "Klasyczne kuchnie", "Bezpłatna wycena", "Nowoczesne kuchnie", "Salon ekspozycyjny", "Zabudowy", "Sklep internetowy", "Wizualizacje 3D", "Sprzęt AGD"] as const;
